In [1]:
import numpy as np

In [2]:
a = np.arange(15)

In [3]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
a = a.reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
a.shape

(3, 5)

## Løysing av likningssett

$$
\begin{bmatrix}
3 & 1 & 2 \\
0 & -3 & 1 \\
1 & 1 & -2
\end{bmatrix}
\begin{bmatrix}
x \\
y \\
z
\end{bmatrix}
=
\begin{bmatrix}
10 \\
-5 \\
7
\end{bmatrix}
$$

In [21]:
A = np.array([[3, 1, 2],[0, -3, 1],[1, 1, -2]])
A

array([[ 3,  1,  2],
       [ 0, -3,  1],
       [ 1,  1, -2]])

In [22]:
B = np.array([[10], [-5], [7]])
B

array([[10],
       [-5],
       [ 7]])

Me veit at:
$$
x = A^{-1} B
$$

In [25]:
x = np.matmul(np.linalg.inv(A), B)

In [26]:
x

array([[ 3.59090909],
       [ 1.31818182],
       [-1.04545455]])